# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13qMQYOAcVLc6Gasz0PSh0KwQl-E--D4s
"""

!pip install scann



import sklearn.datasets as skd
import numpy as np
import scann

# Load data (will download the data if it's the first time loading)
import_data = skd.load_wine(as_frame=True)
# Create a dataframe
create_dataframe = import_data['data'].join(import_data['target'])
# Make the dataset clear for the algorithm to use it
normalized_dataset = create_dataframe/ np.linalg.norm(create_dataframe, axis=1)[:, np.newaxis]
finder = scann.scann_ops_pybind.builder(normalized_dataset, 10, "dot_product").tree(num_leaves=20, num_leaves_to_search=10, training_sample_size=1000).score_ah(2, anisotropic_quantization_threshold=0.2).reorder(100).build()
neighbors, distances = finder.search_batched(normalized_dataset)
print(neighbors)
print(distances)